from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
import zipfile
from pathlib import Path
from typing import Dict, List

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

BASE = Path(__file__).resolve().parent
WORK = BASE / "workspaces"
OUTPUT = BASE / "outputs"
WORK.mkdir(exist_ok=True)
OUTPUT.mkdir(exist_ok=True)

app = FastAPI(title="Legacy to Modernization")
app.mount("/static", StaticFiles(directory=str(BASE / "static")), name="static")


def safe_extract(zip_path: Path, dest: Path) -> None:
    dest = dest.resolve()
    with zipfile.ZipFile(zip_path) as zf:
        for member in zf.infolist():
            entry = Path(member.filename)
            if entry.is_absolute() or member.filename.startswith(("/", "\\")):
                raise HTTPException(400, "Unsafe ZIP entry detected.")
            if member.external_attr >> 16 & 0o170000 == 0o120000:
                raise HTTPException(400, "Unsafe ZIP symlink detected.")
            target = (dest / entry).resolve()
            try:
                target.relative_to(dest)
            except ValueError:
                raise HTTPException(400, "Unsafe ZIP entry detected.")
        zf.extractall(dest)


def cobol_to_python(source: str, name: str) -> str:
    """Heuristic starter converter. Replace with a parser/LLM-powered engine for production."""
    program = Path(name).stem.lower().replace("-", "_").replace(" ", "_")
    lines = ['"""Generated from legacy COBOL source.', 'This starter conversion preserves intent and markers; review before production use.', '"""', "", "from __future__ import annotations", "", "def main() -> None:"]
    working = []
    paragraphs = []
    for raw in source.splitlines():
        s = raw.strip()
        if not s:
            continue
        if re.match(r"^[A-Z0-9-]+\.$", s):
            paragraphs.append(s[:-1].lower().replace("-", "_"))
        m = re.match(r"^01\s+([A-Z0-9-]+)", s)
        if m:
            working.append(m.group(1).lower().replace("-", "_"))
    lines.append(f"    # Source program: {Path(name).name}")
    lines.append(f"    # Converted program: {program}")
    for field in working[:25]:
        lines.append(f"    {field} = None  # COBOL data item")
    if paragraphs:
        for p in paragraphs[:40]:
            lines.append(f"    # TODO: implement paragraph {p} from COBOL")
    lines.append("    print('COBOL conversion scaffold generated successfully')")
    lines += ["", "", "if __name__ == '__main__':", "    main()"]
    return "\n".join(lines) + "\n"


def extract_sql(source: str) -> str:
    statements: List[str] = []
    for m in re.finditer(r"EXEC\s+SQL(.*?)END-EXEC", source, re.I | re.S):
        body = re.sub(r"\s+", " ", m.group(1)).strip()
        if body:
            statements.append(body)
    tables = sorted(set(re.findall(r"\b(?:FROM|JOIN|INTO|UPDATE|TABLE)\s+([A-Z0-9_.$-]+)", source, re.I)))
    ddl = []
    if tables:
        ddl.append("-- Tables referenced by COBOL SQL blocks")
        for table in tables:
            ddl.append(f"-- {table}")
    if statements:
        ddl.append("\n-- Extracted SQL statements")
        for stmt in statements:
            ddl.append(stmt.rstrip(";") + ";")
    else:
        ddl.append("-- No EXEC SQL blocks detected in this source file.")
    return "\n".join(ddl) + "\n"


def discover_cobol(root: Path) -> List[Path]:
    exts = {".cbl", ".cob", ".cobol", ".cpy", ".CBL", ".COB", ".CPY"}
    return [p for p in root.rglob("*") if p.is_file() and p.suffix in exts]


def build_output(source_root: Path, output_dir: Path) -> List[Dict[str, str]]:
    files = discover_cobol(source_root)
    if not files:
        files = [p for p in source_root.rglob("*") if p.is_file() and p.suffix.lower() in {".txt", ".src"}]
    results: List[Dict[str, str]] = []
    for src in files:
        rel = src.relative_to(source_root)
        try:
            text = src.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        py_rel = rel.with_suffix(".py")
        sql_rel = Path("sql") / (rel.stem + ".sql")
        py_path = output_dir / py_rel
        sql_path = output_dir / sql_rel
        py_path.parent.mkdir(parents=True, exist_ok=True)
        sql_path.parent.mkdir(parents=True, exist_ok=True)
        py_path.write_text(cobol_to_python(text, str(rel)), encoding="utf-8")
        sql_path.write_text(extract_sql(text), encoding="utf-8")
        results.append({"source": str(rel), "python": str(py_rel), "sql": str(sql_rel)})
    (output_dir / "README.md").write_text("# Legacy to Modernization output\n\nGenerated by the starter COBOL modernization pipeline.\n\nImportant: generated code is a reviewable scaffold. Production migration should include parser-level validation, business-rule mapping, data-model reconciliation, test generation, and human approval.\n", encoding="utf-8")
    return results


def zip_dir(src_dir: Path, zip_path: Path) -> None:
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in src_dir.rglob("*"):
            if path.is_file():
                zf.write(path, path.relative_to(src_dir))


@app.get("/", response_class=HTMLResponse)
def index() -> str:
    return (BASE / "static" / "index.html").read_text(encoding="utf-8")


@app.post("/api/convert")
async def convert(source_type: str = Form(...), git_url: str | None = Form(default=None), cobol_zip: UploadFile | None = File(default=None)):
    job_id = next(tempfile._get_candidate_names())
    root = WORK / job_id
    output = OUTPUT / job_id
    root.mkdir(parents=True, exist_ok=True)
    output.mkdir(parents=True, exist_ok=True)
    try:
        if source_type == "zip":
            if not cobol_zip or not cobol_zip.filename:
                raise HTTPException(400, "Please upload a COBOL ZIP file.")
            if not cobol_zip.filename.lower().endswith(".zip"):
                raise HTTPException(400, "Only ZIP archives are accepted.")
            incoming = root / "project.zip"
            with incoming.open("wb") as f:
                shutil.copyfileobj(cobol_zip.file, f)
            safe_extract(incoming, root / "src")
            source_root = root / "src"
        elif source_type == "git":
            if not git_url or not re.match(r"^https?://", git_url):
                raise HTTPException(400, "Please provide a valid HTTPS Git URL.")
            source_root = root / "src"
            proc = subprocess.run(["git", "clone", "--depth", "1", git_url, str(source_root)], capture_output=True, text=True, timeout=120)
            if proc.returncode != 0:
                raise HTTPException(400, f"Git clone failed: {proc.stderr[-1200:]}")
        else:
            raise HTTPException(400, "Unsupported source type.")
        results = build_output(source_root, output)
        archive = OUTPUT / f"legacy-to-modernization-{job_id}.zip"
        zip_dir(output, archive)
        return JSONResponse({"job_id": job_id, "message": "Conversion completed.", "files": results, "download_url": f"/api/download/{job_id}", "preview_root": str(output)})
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(500, f"Conversion failed: {exc}")


@app.get("/api/preview/{job_id}")
def preview(job_id: str):
    output = OUTPUT / job_id
    if not output.exists():
        raise HTTPException(404, "Job not found.")
    files = []
    for p in output.rglob("*"):
        if p.is_file():
            rel = str(p.relative_to(output))
            text = p.read_text(encoding="utf-8", errors="ignore")
            files.append({"path": rel, "content": text[:50000]})
    return {"files": sorted(files, key=lambda x: x["path"])}


@app.get("/api/download/{job_id}")
def download(job_id: str):
    archive = OUTPUT / f"legacy-to-modernization-{job_id}.zip"
    if not archive.exists():
        raise HTTPException(404, "Download not found.")
    return FileResponse(archive, filename=archive.name, media_type="application/zip")
